server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babytun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Mysql8.0
  # Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    # 连接池配置
    jedis:
      pool:
        # 最大连接数数
        max-active: 100
        # 最大空闲数
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms
  freemarker:
    suffix: .ftl

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



